#! /bin/bash
# alias: brew tree
#:  * `tree` [args...]
#:    `brew tree` is an alias for `brew deps --installed --formula --tree $(brew leaves --installed-on-request)`
brew deps --installed --formula --tree $(brew leaves --installed-on-request) $* | grep "\S"

orphans=$(brew orphans | sed 's/^/- /')
[[ -z $orphans ]] && exit 0
cat <<END

Orphans:
$orphans
Remove all with: brew autoremove
END
exit 1
