default_flags = "-gh"
show_selection_mark = true
icon_theme = "nerdfont"
quit_on_last_cancel = true

[[imports]]
luma = ["dark", "unknown"]
file = "skins/dark-blue.hjson"

[[imports]]
luma = "light"
file = "skins/solarized-light.hjson"
