[tools]
rust = "latest"
# "cargo:tuckr" = "latest"
"cargo:https://github.com/RaphGL/Tuckr" = "rev:83716ba"
node = "latest"
pnpm = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:@typescript/native-preview" = "latest"

[settings]

[settings.npm]
package_manager = "pnpm"
